fn main {
  // let data = [
  //   0xA9, 0xFF, 0x85, 0x90, 0x8D, 0x00, 0x80, 0x49, 0xCC, 0x4C, 0x02, 0x10,
  // ]
  // let c64 = @lib.C64::new(baseaddress=0x1000, ~data, offset=0x1000)
  // let _ = c64.step() // LDA
  // let mut i = 0
  // while i < 10 {
  //   println("#\(i)")
  //   let _ = c64.step() // STA
  //   let _ = c64.step() // STA
  //   let _ = c64.step() // EOR
  //   let _ = c64.step() // JMP
  //   i += 1
  // }

  // nestest()
  sidtest()
}
